export const SET_PLACE_BY_ID = 'SET_PLACE_BY_ID';
export const FETCH_PLACE_BY_ID = 'FETCH_PLACE_BY_ID';
export const FETCH_TYPES_LIST = 'FETCH_TYPES_LIST';
export const SET_TYPES_LIST = 'SET_TYPES_LIST';
export const FETCH_PLACES_LIST_BY_TYPE = 'FETCH_PLACES_LIST_BY_TYPE';
export const SET_PLACES_LIST_BY_TYPE = 'SET_PLACES_LIST_BY_TYPE';